# Generated by Django 5.1.6 on 2025-02-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="auth",
            new_name="author",
        ),
    ]
